package com.redblue.red.modules.tacz;

import com.redblue.red.core.AttackModule;
import com.redblue.red.core.config.ConfigParam;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.fml.ModList;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.List;

/**
 * TACZ-02: 快速射击 (Rapid Fire) — v3 Reflection-into-native approach
 *
 * Instead of constructing and sending ClientMessagePlayerShoot packets ourselves
 * (which caused persistent drift/timestamp issues), this version reflects into
 * TACZ's own client-side shoot code path:
 *
 * 1. Get IClientPlayerGunOperator from LocalPlayer (via mixin cast)
 * 2. Get LocalPlayerDataHolder via getDataHolder()
 * 3. Reset cooldown fields (clientShootTimestamp, isShootRecorded, clientStateLock,
 *    clientClickButtonTimestamp) to bypass client-side cooldown checks
 * 4. Call IClientPlayerGunOperator.shoot() — TACZ generates proper timestamps internally
 *
 * This way:
 * - Timestamps are always valid (generated by TACZ's own System.currentTimeMillis())
 * - Packet format is always correct
 * - No baseTimestamp/syncWallClock tracking needed
 * - Only fires when holding a TACZ gun (native code checks IGun)
 */
public class TACZ02_RapidFire implements AttackModule {

    private static final Logger LOGGER = LoggerFactory.getLogger("TACZ02");

    // TACZ class names for reflection
    private static final String IGUN_CLASS = "com.tacz.guns.api.item.IGun";
    private static final String ICLIENT_OPERATOR_CLASS =
            "com.tacz.guns.api.client.gameplay.IClientPlayerGunOperator";
    private static final String DATA_HOLDER_CLASS =
            "com.tacz.guns.client.gameplay.LocalPlayerDataHolder";
    private static final String SHOOT_RESULT_CLASS = "com.tacz.guns.api.entity.ShootResult";

    // Reflection cache
    private static boolean reflectionResolved = false;
    private static boolean reflectionOk = false;
    private static Method fromLocalPlayerMethod;   // IClientPlayerGunOperator.fromLocalPlayer(LocalPlayer)
    private static Method shootMethod;             // IClientPlayerGunOperator.shoot()
    private static Method getDataHolderMethod;     // IClientPlayerGunOperator.getDataHolder()
    private static Method igunGetOrNullMethod;     // IGun.getIGunOrNull(ItemStack)
    private static Field clientShootTimestampField; // LocalPlayerDataHolder.clientShootTimestamp
    private static Field isShootRecordedField;      // LocalPlayerDataHolder.isShootRecorded
    private static Field clientStateLockField;      // LocalPlayerDataHolder.clientStateLock
    private static Field clientClickButtonTsField;  // LocalPlayerDataHolder.clientClickButtonTimestamp (static)
    private static Object shootResultSuccess;       // ShootResult.SUCCESS enum value

    // State tracking
    private boolean wasAttackDown = false;
    private int burstCooldownTicks = 0;
    private int totalShotsFired = 0;
    private int totalShotsSuccess = 0;

    private final List<ConfigParam> params = List.of(
            ConfigParam.ofBool("enabled", "启用", false),
            ConfigParam.ofInt("fire_interval", "射击间隔(tick)", 2, 1, 10),
            ConfigParam.ofInt("burst_count", "每次发数", 3, 1, 6)
    );

    @Override public String id() { return "tacz02_rapid_fire"; }
    @Override public String name() { return "快速射击"; }
    @Override public String description() { return "反射调用TACZ原生射击方法，绕过客户端冷却实现快速射击"; }

    @Override
    public String getTutorial() {
        return "[使用方法]\n"
                + "1. 启用模块后，手持TACZ枪械\n"
                + "2. 按住开火键，模块自动重置冷却并调用原生shoot()\n"
                + "3. 每次tick发送burst_count次射击\n\n"
                + "[参数说明]\n"
                + "射击间隔：每次burst之间的tick间隔(1tick=50ms)\n"
                + "每次发数：每次burst调用shoot()的次数\n\n"
                + "[原理 v3]\n"
                + "不再自己构造射击包，而是反射进TACZ原生代码：\n"
                + "  1) 获取 IClientPlayerGunOperator (LocalPlayer的mixin接口)\n"
                + "  2) 获取 LocalPlayerDataHolder，重置冷却字段\n"
                + "  3) 调用原生 shoot()，TACZ自己生成正确的时间戳和包\n"
                + "优势：时间戳永远正确，不会drift，不会卡壳";
    }

    @Override
    public boolean isAvailable() {
        return ModList.get().isLoaded("tacz");
    }

    @Override
    public List<ConfigParam> getConfigParams() { return params; }

    @Override
    public void execute(Minecraft mc) {
        if (mc.player == null) return;
        fireBurst(mc);
    }

    @Override
    public void tick(Minecraft mc) {
        if (mc.player == null || mc.level == null) return;

        if (burstCooldownTicks > 0) {
            burstCooldownTicks--;
        }

        boolean attackDown = mc.options.keyAttack.isDown();

        // Only act when holding a TACZ gun
        if (!isHoldingTaczGun(mc)) {
            wasAttackDown = attackDown;
            return;
        }

        if (attackDown && !wasAttackDown) {
            // First press
            fireBurst(mc);
            burstCooldownTicks = getParam("fire_interval").map(ConfigParam::getInt).orElse(2);
        } else if (attackDown && burstCooldownTicks <= 0) {
            // Held down, cooldown expired
            fireBurst(mc);
            burstCooldownTicks = getParam("fire_interval").map(ConfigParam::getInt).orElse(2);
        }

        wasAttackDown = attackDown;
    }

    /**
     * Check if the player is holding a TACZ gun via IGun interface check.
     */
    private boolean isHoldingTaczGun(Minecraft mc) {
        if (mc.player == null) return false;
        resolveReflection();
        if (!reflectionOk || igunGetOrNullMethod == null) return false;

        try {
            ItemStack mainHand = mc.player.getMainHandItem();
            Object igun = igunGetOrNullMethod.invoke(null, mainHand);
            return igun != null;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Fire a burst by reflecting into TACZ's native shoot path.
     *
     * For each shot in the burst:
     * 1. Reset clientShootTimestamp to far past (so cooldown check passes)
     * 2. Set isShootRecorded = true (so the "not recorded" early-return is skipped)
     * 3. Set clientStateLock = false (so the state lock check is skipped)
     * 4. Reset clientClickButtonTimestamp to now (so the 50ms debounce passes)
     * 5. Call IClientPlayerGunOperator.shoot()
     *
     * TACZ's shoot() internally does:
     *   data.clientShootTimestamp = System.currentTimeMillis()
     *   sendToServer(new ClientMessagePlayerShoot(clientShootTimestamp - clientBaseTimestamp))
     * So the timestamp is always correct relative to the server's baseTimestamp.
     */
    private void fireBurst(Minecraft mc) {
        resolveReflection();
        if (!reflectionOk) {
            chatLog("[TACZ02] Reflection failed, cannot fire");
            return;
        }

        int count = getParam("burst_count").map(ConfigParam::getInt).orElse(3);

        try {
            // Get IClientPlayerGunOperator from player
            Object operator = fromLocalPlayerMethod.invoke(null, mc.player);
            if (operator == null) {
                chatLog("[TACZ02] operator is null");
                return;
            }

            // Get the data holder
            Object dataHolder = getDataHolderMethod.invoke(operator);
            if (dataHolder == null) {
                chatLog("[TACZ02] dataHolder is null");
                return;
            }

            int successCount = 0;
            StringBuilder log = new StringBuilder("[TACZ02] Burst: ");

            for (int i = 0; i < count; i++) {
                // Reset cooldown fields before each shot
                resetCooldowns(dataHolder);

                // Call native shoot()
                Object result = shootMethod.invoke(operator);
                String resultName = result != null ? result.toString() : "null";
                boolean success = (result == shootResultSuccess);

                if (success) {
                    successCount++;
                }
                log.append(String.format("#%d=%s ", i, resultName));

                totalShotsFired++;
                if (success) totalShotsSuccess++;
            }

            log.append(String.format("(%d/%d ok, total=%d/%d)",
                    successCount, count, totalShotsSuccess, totalShotsFired));
            chatLog(log.toString());

        } catch (Exception e) {
            LOGGER.error("[TACZ02] fireBurst failed", e);
            chatLog("[TACZ02] Error: " + e.getMessage());
        }
    }

    /**
     * Reset TACZ client-side cooldown fields so the next shoot() call passes all checks.
     */
    private void resetCooldowns(Object dataHolder) throws Exception {
        // clientShootTimestamp = 0 (far in the past relative to currentTimeMillis)
        // This makes getCoolDown() return a large negative = 0 after max(x,0)
        clientShootTimestampField.setLong(dataHolder, 0L);

        // isShootRecorded = true (skip the "not recorded" early return)
        isShootRecordedField.setBoolean(dataHolder, true);

        // clientStateLock = false (skip the state lock check)
        clientStateLockField.setBoolean(dataHolder, false);

        // clientClickButtonTimestamp = now (skip the 50ms debounce)
        clientClickButtonTsField.setLong(null, System.currentTimeMillis());
    }

    /** Display debug message in chat */
    private void chatLog(String msg) {
        Minecraft mc = Minecraft.getInstance();
        if (mc.player != null) {
            mc.player.displayClientMessage(Component.literal(msg), false);
        }
    }

    /**
     * Resolve all TACZ reflection handles (once, cached).
     */
    private static synchronized void resolveReflection() {
        if (reflectionResolved) return;
        reflectionResolved = true;

        try {
            // IClientPlayerGunOperator
            Class<?> operatorClass = Class.forName(ICLIENT_OPERATOR_CLASS);
            fromLocalPlayerMethod = operatorClass.getMethod(
                    "fromLocalPlayer", net.minecraft.client.player.LocalPlayer.class);
            shootMethod = operatorClass.getMethod("shoot");
            getDataHolderMethod = operatorClass.getMethod("getDataHolder");

            // IGun.getIGunOrNull(ItemStack) — static method
            Class<?> igunClass = Class.forName(IGUN_CLASS);
            igunGetOrNullMethod = igunClass.getMethod("getIGunOrNull", ItemStack.class);

            // LocalPlayerDataHolder fields
            Class<?> holderClass = Class.forName(DATA_HOLDER_CLASS);

            clientShootTimestampField = holderClass.getDeclaredField("clientShootTimestamp");
            clientShootTimestampField.setAccessible(true);

            isShootRecordedField = holderClass.getDeclaredField("isShootRecorded");
            isShootRecordedField.setAccessible(true);

            clientStateLockField = holderClass.getDeclaredField("clientStateLock");
            clientStateLockField.setAccessible(true);

            clientClickButtonTsField = holderClass.getDeclaredField("clientClickButtonTimestamp");
            clientClickButtonTsField.setAccessible(true);

            // ShootResult.SUCCESS
            Class<?> resultClass = Class.forName(SHOOT_RESULT_CLASS);
            Field successField = resultClass.getField("SUCCESS");
            shootResultSuccess = successField.get(null);

            reflectionOk = true;
            LOGGER.info("[TACZ02] Reflection resolved successfully (v3 native shoot path)");
        } catch (Exception e) {
            LOGGER.error("[TACZ02] Failed to resolve reflection handles", e);
            reflectionOk = false;
        }
    }
}
